export type ThemeName = 'light' | 'dark' | 'lavender';

export const THEMES: Record<ThemeName, any> = {
  light: {
    bg: '#FFF8F0',
    card: '#FFFFFF',
    text: '#2D2D2D',
    sub: '#8B8680',
    border: '#F0E8DC',
    accent: '#4A7C59',
    cardBg: '#FFF5EB',
    warmBg: '#FFF8F0',
    greenCard: '#2D5A3D',
    cream: '#F5EDE0',
    input: '#F5EDE0',
    isDark: false,
  },
  dark: {
    bg: '#1A1A2E',
    card: '#25253D',
    text: '#F5F0E8',
    sub: '#A09B8C',
    border: '#3A3A52',
    accent: '#4A7C59',
    cardBg: '#2A2A42',
    warmBg: '#1A1A2E',
    greenCard: '#2D5A3D',
    cream: '#25253D',
    input: '#1A1A2E',
    isDark: true,
  },
  lavender: {
    bg: '#F8F7FF',
    card: '#FFFFFF',
    text: '#2E2542',
    sub: '#786C94',
    border: '#EBE7F5',
    accent: '#7C5DBA',
    cardBg: '#FAF9FF',
    warmBg: '#F8F7FF',
    greenCard: '#4D3C6E',
    cream: '#F2F0FF',
    input: '#F2F0FF',
    isDark: false,
  }
};
