export type ThemeName = 'light' | 'dark' | 'lavender' | 'ocean' | 'snow';

export const THEMES: Record<ThemeName, any> = {
  light: {
    bg: '#FFF8F0',
    card: '#FFFFFF',
    text: '#2D2D2D',
    sub: '#8B8680',
    border: '#F0E8DC',
    accent: '#4A7C59',
    cardBg: '#FFF5EB',
    warmBg: '#FFF8F0',
    greenCard: '#2D5A3D',
    cream: '#F5EDE0',
    input: '#F5EDE0',
    isDark: false,
  },
  dark: {
    bg: '#1A1A2E',
    card: '#25253D',
    text: '#F5F0E8',
    sub: '#A09B8C',
    border: '#3A3A52',
    accent: '#4A7C59',
    cardBg: '#2A2A42',
    warmBg: '#1A1A2E',
    greenCard: '#2D5A3D',
    cream: '#25253D',
    input: '#1A1A2E',
    isDark: true,
  },
  lavender: {
    bg: '#F8F7FF',
    card: '#FFFFFF',
    text: '#2E2542',
    sub: '#786C94',
    border: '#EBE7F5',
    accent: '#7C5DBA',
    cardBg: '#FAF9FF',
    warmBg: '#F8F7FF',
    greenCard: '#4D3C6E',
    cream: '#F2F0FF',
    input: '#F2F0FF',
    isDark: false,
  },
  ocean: {
    bg: '#F0F9FA',
    card: '#FFFFFF',
    text: '#1A3A3A',
    sub: '#648E8E',
    border: '#E0F2F3',
    accent: '#008080',
    cardBg: '#F5FCFD',
    warmBg: '#F0F9FA',
    greenCard: '#004D40',
    cream: '#E0F2F3',
    input: '#E0F2F3',
    isDark: false,
  },
  snow: {
    bg: '#FFFFFF',
    card: '#FFFFFF',
    text: '#1E293B',
    sub: '#64748B',
    border: '#F1F5F9',
    accent: '#4A7C59',
    cardBg: '#F8FAFC',
    warmBg: '#FFFFFF',
    greenCard: '#0F172A',
    cream: '#F1F5F9',
    input: '#F1F5F9',
    isDark: false,
  }
};
